routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/articles/fetch', [ArticleController::class, 'fetch'])->name('articles.fetch');
Route::get('/', [ArticleController::class, 'index']);
Route::resource('articles', ArticleController::class);
Route::resource('playlists', PlaylistController::class);
Route::resource('playlists.videos', VideoController::class)->shallow();

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = ['title', 'description', 'author'];
}

app/Models/Playlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Playlist extends Model
{
    use HasFactory;

    public function videos()
{
    return $this->hasMany(Video::class);
}
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    use HasFactory;
    
    public function playlist()
{
    return $this->belongsTo(Playlist::class);
}
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use App\Models\Video;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
{
    $articles = Article::all();
    return view('articles.index', compact('articles'));
}

public function create()
{
    return view('articles.create');
}

public function show(Article $article)
{
    return view('articles.show', compact('article'));
}

public function store(Request $request)
{
    Article::create($request->all());
    return redirect()->route('articles.index');
}

public function edit(Article $article)
{
    $videos = Video::where('playlist_id', $article->id)->get();
    return view('articles.edit', compact('article', 'videos'));
}

public function update(Request $request, Article $article)
{
    $article->update($request->all());
    return redirect()->route('articles.index');

    if ($request->video_title && $request->video_url && $request->video_author) {
        Video::create([
            'playlist_id' => $article->id,
            'title' => $request->video_title,
            'url' => $request->video_url,
            'author' => $request->video_author
        ]);
    }

    return redirect()->route('articles.index')->with('success', 'Article and associated video updated successfully.');
}

public function destroy(Article $article)
{
    $article->delete();
    return redirect()->route('articles.index');
}

public function fetch()
{
    $articles = Article::all();
    return response()->json($articles);
}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PlaylistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Playlist;
use Illuminate\Http\Request;

class PlaylistController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $playlists = Playlist::all();
        return view('playlists.index', compact('playlists'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('playlists.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        Playlist::create($request->all());
        return redirect()->route('playlists.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Playlist;
use App\Models\Video;
use Illuminate\Http\Request;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Playlist $playlist)
    {
        return view('videos.index', ['videos' => $playlist->videos, 'playlist' => $playlist]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Playlist $playlist)
    {
        return view('videos.create', compact('playlist'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request, Playlist $playlist)
    {
        $playlist->videos()->create($request->all());
        return redirect()->route('playlists.videos.index', $playlist->id);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Adicionar novo livro</h2>
    <form action="{{ route('articles.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="title">Título:</label>
            <input type="text" name="title" id="title" class="form-control">
        </div>
        
        <div class="form-group">
            <label for="description">Descrição:</label>
            <input type="text" name="description" id="description" class="form-control">
        </div>
        
        <div class="form-group">
            <label for="author">Autor:</label>
            <input type="text" name="author" id="author" class="form-control">
        </div>
        
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Editar</h2>

    <form action="{{ route('articles.update', $article->id) }}" method="POST">
        @csrf
        @method('PUT')

        <!-- Article Fields -->
        <div class="form-group">
            <label for="title">Título</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $article->title }}">
        </div>

        <div class="form-group">
            <label for="description">Descrição</label>
            <textarea class="form-control" id="description" name="description" rows="3">{{ $article->description }}</textarea>
        </div>

        <div class="form-group">
            <label for="author">Autor</label>
            <input type="text" class="form-control" id="author" name="author" value="{{ $article->author }}">
        </div>

        <!-- Video Fields -->
        <hr>
        <h3>Playlist de vídeos</h3>

        @foreach($videos as $video)
            <div class="card mt-2">
                <div class="card-body">
                    <h5>{{ $video->title }}</h5>
                    <p>{{ $video->url }}</p>
                    <p>{{ $video->author }}</p>
                </div>
            </div>
        @endforeach

        <hr>
        <h3>Adicionar novo vídeo</h3>
        <div class="form-group">
            <label for="video_title">título</label>
            <input type="text" class="form-control" id="video_title" name="video_title">
        </div>

        <div class="form-group">
            <label for="video_url">Vídeo URL</label>
            <input type="text" class="form-control" id="video_url" name="video_url">
        </div>

        <div class="form-group">
            <label for="video_author">Vídeo Autor</label>
            <input type="text" class="form-control" id="video_author" name="video_author">
        </div>

        <button type="submit" class="btn btn-primary">Atualizar</button>
        <a href="{{ route('articles.index') }}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div class="container mt-4">
    <h1 class="text-primary mb-4">Projeto Livraria Online</h1>
    
    <a href="{{ route('articles.create') }}" class="btn btn-outline-success mb-4">Adicionar novo livro</a>

    <div class="list-group" id="articles-list">

    </div>
</div>

<script>
    $(document).ready(function() {
        $.ajax({
            url: '{{ route('articles.fetch') }}',
            method: 'GET',
            dataType: 'json',
            success: function(data) {
                $.each(data, function(key, article) {
                    $('#articles-list').append(`
                        <a href="/articles/${article.id}" class="list-group-item list-group-item-action mb-2">
                            <h4>${article.title}</h4>
                            <p class="mb-0">${article.description.length > 150 ? article.description.substring(0, 150) + '...' : article.description}</p>
                            <small class="text-muted">Autor: ${article.author}</small>
                        </a>
                    `);
                });
            },
            error: function(error) {
                console.log('Erro ao carregar artigos:', error);
            }
        });
    });
</script>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h2 class="text-primary">{{ $article->title }}</h2>
        </div>
        <div class="card-body">
            <p class="card-text text-dark">{{ $article->description }}</p>
            <p class="text-muted">Autor: {{ $article->author }}</p>

            <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-warning">Editar</a>
            <form action="{{ route('articles.destroy', $article->id) }}" method="POST" class="d-inline">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Deletar</button>
            </form>
        </div>

    </div>

    <a href="{{ route('articles.index') }}" class="btn btn-secondary mt-4">Voltar</a>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SectoTech</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="bg-dark text-white">

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/playlists/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Create New Playlist</h2>
    <form action="{{ route('playlists.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
@endsection

resources/views/playlists/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Playlists</h2>
    <a href="{{ route('playlists.create') }}" class="btn btn-primary mb-3">Add New Playlist</a>
    <ul class="list-group">
        @foreach($playlists as $playlist)
            <li class="list-group-item">
                {{ $playlist->title }}
                <a href="{{ route('playlists.videos.index', $playlist->id) }}" class="btn btn-info btn-sm float-right">View Videos</a>
            </li>
        @endforeach
    </ul>
</div>
@endsection

resources/views/videos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Add Video to Playlist: {{ $playlist->title }}</h2>
    <form action="{{ route('playlists.videos.store', $playlist->id) }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>

        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url">
        </div>

        <div class="form-group">
            <label for="author">Author</label>
            <input type="text" class="form-control" id="author" name="author">
        </div>

        <button type="submit" class="btn btn-primary">Add Video</button>
    </form>
</div>
@endsection

resources/views/videos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <h2>Videos in Playlist: {{ $playlist->title }}</h2>
    <a href="{{ route('playlists.videos.create', $playlist->id) }}" class="btn btn-primary mb-3">Add New Video</a>
    <ul class="list-group">
        @foreach($videos as $video)
            <li class="list-group-item">
                <strong>{{ $video->title }}</strong> by {{ $video->author }}
                <a href="{{ $video->url }}" target="_blank" class="btn btn-info btn-sm float-right">Watch Video</a>
            </li>
        @endforeach
    </ul>
</div>
@endsection